-- Lesson plans for IGCSE Maths/Chem and International A-Level Maths/Chem
insert into lessons (course_id,num,title,objectives,homework) values
('igcse-math',1,'Diagnostic & Course Roadmap','Sit the baseline diagnostic; map against the Extended (CIE 0580 / Edexcel 4MA1) syllabus; set target grade 7-9 / A*.','Diagnostic corrections; list your three weakest topics.'),
('igcse-math',2,'Number, Indices & Standard Form','Operations, fractions, percentages; index laws; standard form; bounds and rounding.','Number skills circuit.'),
('igcse-math',3,'Algebra: Expressions, Expansion & Factorising','Manipulate expressions; expand and factorise including quadratics; algebraic fractions.','Algebra manipulation drill.'),
('igcse-math',4,'Equations, Inequalities & Rearranging Formulae','Solve linear and quadratic equations; inequalities; rearrange formulae.','Equations and inequalities worksheet.'),
('igcse-math',5,'End of Topic Test: Number & Algebra','Sit the end-of-topic test on number and algebra; review technique with mark scheme.','Test corrections.'),
('igcse-math',6,'Sequences & Functions','nth term incl. quadratic sequences; function notation; composite and inverse functions.','Sequences and functions set.'),
('igcse-math',7,'Ratio, Proportion & Percentages','Sharing ratios; direct/inverse proportion; compound interest and reverse percentages.','Proportion exam questions.'),
('igcse-math',8,'Coordinate Geometry & Linear Graphs','Straight-line equations; gradients; midpoints; real-life and distance-time graphs.','Coordinate geometry worksheet.'),
('igcse-math',9,'Quadratic Equations & Graphs','Solve quadratics by factorising, formula and completing the square; sketch parabolas.','Quadratics circuit.'),
('igcse-math',10,'Mid-Course Assessment','Sit the mid-course assessment (number, algebra, graphs); mark-scheme review.','Full corrections.'),
('igcse-math',11,'Geometry: Angles, Polygons & Circle Theorems','Angle rules; polygons; all circle theorems with reasons.','Circle theorems proof practice.'),
('igcse-math',12,'Mensuration & Similar Shapes','Area, surface area and volume; arcs and sectors; similar shapes and scale factors.','Mensuration problem set.'),
('igcse-math',13,'Trigonometry: Right-angled, Sine & Cosine Rules','SOHCAHTOA; sine and cosine rules; area of a triangle; 3D trigonometry.','Trigonometry mixed worksheet.'),
('igcse-math',14,'Vectors & Transformations','Column vectors; vector geometry; transformations and combinations.','Vectors and transformations set.'),
('igcse-math',15,'Probability & Statistics','Tree and Venn diagrams; set notation; averages from tables; histograms and cumulative frequency.','Probability and statistics exam set.'),
('igcse-math',16,'Final Assessment & Exam Technique','Sit the final assessment under timed conditions; full exam-technique debrief and revision plan.','Targeted revision list.'),
('igcse-chem',1,'Diagnostic & Course Roadmap','Sit the baseline diagnostic; map against the IGCSE Chemistry (CIE 0620 / Edexcel 4CH1) syllabus; lab orientation.','Diagnostic corrections.'),
('igcse-chem',2,'States of Matter, Particles & Separation','Particle model; changes of state; diffusion; mixtures and separation techniques.','Particle model and separation worksheet.'),
('igcse-chem',3,'Atomic Structure & the Periodic Table','Atomic structure; isotopes; electronic configuration; periodic trends and groups.','Atomic structure questions.'),
('igcse-chem',4,'Bonding & Structure','Ionic, covalent and metallic bonding; giant and simple structures; properties.','Bonding exam questions.'),
('igcse-chem',5,'End of Topic Test: Structure & Bonding','Sit the end-of-topic test on structure and bonding; review with mark scheme.','Test corrections.'),
('igcse-chem',6,'Stoichiometry & Mole Calculations','Relative masses; moles; reacting masses; concentrations; yields.','Mole calculations circuit.'),
('igcse-chem',7,'Electrochemistry & Redox','Electrolysis; oxidation and reduction; reactivity series and displacement.','Electrochemistry and redox worksheet.'),
('igcse-chem',8,'Mid-Course Assessment','Sit the mid-course assessment; mark-scheme review.','Full corrections.'),
('igcse-chem',9,'Energetics & Rates of Reaction','Exothermic/endothermic; energy profiles; collision theory; rate factors and graphs.','Energetics and rates set.'),
('igcse-chem',10,'Equilibria, Acids, Bases & Salts','Reversible reactions; acids, bases, pH; preparing salts; titrations.','Acids and salts problem set.'),
('igcse-chem',11,'Organic Chemistry','Crude oil; alkanes, alkenes, alcohols and carboxylic acids; polymers.','Organic chemistry worksheet.'),
('igcse-chem',12,'Experimental Techniques & Chemical Analysis','Apparatus and measurement; tests for ions and gases; chromatography; practical paper technique.','Analysis six-mark practice.'),
('igcse-chem',13,'Final Assessment & Exam Technique','Sit the final assessment; exam-technique debrief and revision plan.','Targeted revision list.'),
('ial-math',1,'Diagnostic & Course Roadmap','Sit the baseline diagnostic; map against Edexcel IAL units (Pure, Statistics, Mechanics); set A* plan.','Diagnostic corrections.'),
('ial-math',2,'Pure: Algebra, Surds & Indices','Surds and indices; algebraic manipulation; partial fractions; proof.','Algebra and surds worksheet.'),
('ial-math',3,'Pure: Quadratics, Inequalities & Simultaneous Equations','Completing the square; discriminant; inequalities; simultaneous equations.','Quadratics exam set.'),
('ial-math',4,'Pure: Coordinate Geometry & Circles','Straight lines; circles; tangents; parametric intro.','Coordinate geometry questions.'),
('ial-math',5,'Pure: Binomial & Sequences/Series','Binomial expansion; arithmetic/geometric series; sigma notation.','Binomial and series set.'),
('ial-math',6,'End of Topic Test: Pure 1','Sit the end-of-topic test on Pure 1 content; review with mark scheme.','Test corrections.'),
('ial-math',7,'Pure: Trigonometry & Identities','Radians; trig graphs; identities; compound and double angles; solving equations.','Trigonometry worksheet.'),
('ial-math',8,'Pure: Exponentials & Logarithms','e and ln; laws of logs; exponential modelling.','Exponential modelling set.'),
('ial-math',9,'Pure: Differentiation','First principles; rules of differentiation; tangents, stationary points and optimisation.','Differentiation drill.'),
('ial-math',10,'Mid-Course Assessment','Sit the mid-course assessment (Pure); mark-scheme review and technique audit.','Full corrections.'),
('ial-math',11,'Pure: Integration','Indefinite and definite integration; areas; differential equations.','Integration circuit.'),
('ial-math',12,'Pure: Further Trig, Parametric & Numerical Methods','Reciprocal trig; parametric differentiation; iteration and trapezium rule.','Further pure worksheet.'),
('ial-math',13,'Pure: Vectors','2D/3D vectors; magnitude; scalar product; lines in space.','Vectors problem set.'),
('ial-math',14,'Statistics: Data, Probability & Distributions','Data presentation; probability; discrete random variables; expectation.','Statistics worksheet.'),
('ial-math',15,'Statistics: Binomial, Normal & Hypothesis Testing','Binomial and normal distributions; hypothesis testing; correlation and regression.','Hypothesis testing exam set.'),
('ial-math',16,'End of Topic Test: Applied','Sit the end-of-topic test on Statistics; review with mark scheme.','Test corrections.'),
('ial-math',17,'Mechanics: Kinematics & SUVAT','Displacement-velocity-acceleration; SUVAT; motion graphs.','Kinematics problem set.'),
('ial-math',18,'Mechanics: Forces, Moments & Projectiles','F=ma; connected particles; friction; moments; projectile motion.','Mechanics mixed circuit.'),
('ial-math',19,'Final Assessment & Exam Technique','Sit the final assessment under timed conditions; full debrief and revision plan.','Targeted revision list.'),
('ial-chem',1,'Diagnostic & Course Roadmap','Sit the baseline diagnostic; map against Edexcel IAL Chemistry units; practical endorsement overview.','Diagnostic corrections.'),
('ial-chem',2,'Atomic Structure & the Mole','Electron configuration; mass spectrometry; moles, titrations and gas calculations.','Amount-of-substance circuit.'),
('ial-chem',3,'Bonding & Structure','Ionic, covalent, metallic bonding; shapes (VSEPR); polarity; intermolecular forces.','Bonding exam questions.'),
('ial-chem',4,'Energetics I','Enthalpy changes; calorimetry; Hess''s law; bond enthalpies.','Energetics calculation set.'),
('ial-chem',5,'End of Topic Test: Foundations','Sit the end-of-topic test on structure, bonding and energetics; review with mark scheme.','Test corrections.'),
('ial-chem',6,'Kinetics & Equilibrium I','Collision theory; Maxwell-Boltzmann; rate factors; dynamic equilibrium and Kc.','Kinetics and equilibrium worksheet.'),
('ial-chem',7,'Redox & Inorganic: Periodicity and Groups','Oxidation states; half equations; periodic trends; group chemistry.','Inorganic trends questions.'),
('ial-chem',8,'Organic I: Alkanes, Alkenes, Halogenoalkanes & Alcohols','Nomenclature; substitution and addition mechanisms; alcohol reactions; analysis (IR/MS).','Organic mechanisms drill.'),
('ial-chem',9,'Mid-Course Assessment','Sit the mid-course assessment; mark-scheme review.','Full corrections.'),
('ial-chem',10,'Thermodynamics & Rate Equations','Born-Haber; entropy and Gibbs; rate equations; Arrhenius.','Thermodynamics and kinetics set.'),
('ial-chem',11,'Equilibria Kp, Acids & Buffers, Electrochemistry','Kp; pH, Ka and buffers; electrode potentials and cells.','Acids and electrochemistry problem set.'),
('ial-chem',12,'Transition Metals & Inorganic II','Complex ions; colour; ligand substitution; redox titrations.','Transition metals questions.'),
('ial-chem',13,'Organic II: Aromatics, Carbonyls, Polymers & Spectroscopy','Benzene chemistry; carbonyls and acids; condensation polymers; NMR structure determination.','Synoptic organic + NMR problems.'),
('ial-chem',14,'Final Assessment & Exam Technique','Sit the final assessment; exam-technique debrief and revision plan.','Targeted revision list.')
on conflict (course_id,num) do nothing;
